### ISSUE TITLE
New users unable to register on pygame.org.

### ISSUE THREAD

**Issue by abhiii5459** [pygame/pygameweb#37]
So I tried registering on the website and it threw me an Internal Server error 

[pygame Internal Server Error Image ](https://imgur.com/a/xDDJy).
I set up a local version after side stepping a couple of  migration issues (thanks to commenting them out as in https://github.com/pygame/pygameweb/issues/10), and it looks like the server .env file might not be configured correctly i.e the "E-Mail Setup" section.

After I tested with a local updated version of [.env](https://imgur.com/a/kc3Uh), I was able to register a new user  [locally](https://imgur.com/a/jUDOx). 

IMO, this is the resolution. If not, there's still a problem.

**Comment by illume** [comment]
Hi,

It looks like it is the spam protection, and not the email configuration. There is some spam protection which to the user looks like a failure when it kicks in. Often because the ip address of the person signing up has made its way into a spam blacklist somehow. (not suggesting you're a spammer here, addresses get caught up in there sometimes by mistake). I do use quite well maintained spam block lists, but I'm afraid they are not always accurate.

If you privately message me your email I can sign you up.

cheers,
