### ISSUE TITLE
project page not displaying release descriptions

### ISSUE THREAD

**Issue by gummbum** [pygame/pygameweb#5]
Howdy,

I notice the view-project page displays Summary and Description for the project, but the Description I add for each release does not appear anywhere. I poked around quite a bit and could not figure out what is going on with it. It seems the project Description takes precedence, and maybe even gets copied to the release Description (sometimes - this may just be an oddity that emerged and was resolved at some point).

Here is the project page I'm currently struggling with. http://pygame.org/project/3081

**Comment by illume** [comment]
Seems to put it there.  This text is the 'description' right? 
"""
The quickest HUD in town. Put things in the HUD. Update the things with the efficient updater. Render the HUD on any surface. Have more than one HUD. Change the effects on the fly. Pure huddy hudness. * Release 2.1.0 added support for DR0ID's tweening module, offering variety in shading patterns. * Release 2.0.0 added gradient font coloring via PixelArray. No numpy required. This was an experiment. It turned out pretty well.
"""

Looks like it is going on here: http://pygame.org/project/3081

**Comment by gummbum** [comment]
That is the project description.

The release description is this:

"""
Added support for DR0ID's tweening module for a nice variety of shading 
patterns. And a tweens demo.

A tip o' the hat to DR0ID and pyknic: https://bitbucket.org/dr0id/pyknic.
"""

**Comment by illume** [comment]
This is fixed now, it'll be up soon in the next release.
